package dev.bettermapx;
import net.minecraft.client.gui.DrawContext;import net.minecraft.client.gui.screen.Screen;import net.minecraft.text.Text;
public final class SettingsScreen extends Screen{
 private final BetterMapX mod;private final Screen parent;private int tab,px,py;
 public SettingsScreen(BetterMapX m,Screen p){super(Text.literal("Ajustes"));mod=m;parent=p;}
 @Override protected void init(){px=width/2-180;py=Math.max(12,height/2-150);int x=px+12,y=py+34;Config c=mod.config;
  String[] tabs={"Mapa","Marcador","Glow + ESP"};for(int i=0;i<3;i++){final int n=i;addDrawableChild(SilverButton.make(Text.literal(tabs[i]),b->{tab=n;clearAndInit();}).dimensions(x+i*112,py+8,108,20).selected(tab==i).build());}
  if(tab==0){slide(x,y,"Tamanho",c.size,96,320,v->c.size=(int)Math.round(v),v->Math.round(v)+" px");slide(x,y+27,"Zoom minimapa",c.zoom,.1,8,v->c.zoom=v,v->String.format("%.2fx",v));slide(x,y+54,"Zoom inicial",c.worldMapZoom,.1,8,v->c.worldMapZoom=v,v->String.format("%.2fx",v));slide(x,y+81,"Opacidade",c.opacity,.25,1,v->c.opacity=v,v->Math.round(v*100)+"%");slide(x,y+108,"Margem",c.margin,0,100,v->c.margin=(int)Math.round(v),v->Math.round(v)+" px");slide(x,y+135,"Passo Y",c.layerStep,4,64,v->c.layerStep=(int)Math.round(v),v->Math.round(v)+" blocos");slide(x,y+162,"Alcance Y",c.verticalRange,8,64,v->c.verticalRange=(int)Math.round(v),v->"± "+Math.round(v));}
  else if(tab==1){slide(x,y,"Player minimapa",c.playerMarkerScaleMinimap,.25,2,v->c.playerMarkerScaleMinimap=v,v->Math.round(v*100)+"%");slide(x,y+27,"Player mapa cheio",c.playerMarkerScaleFullMap,.25,2,v->c.playerMarkerScaleFullMap=v,v->Math.round(v*100)+"%");toggle("Minimapa",c.minimap,x,y+58,164,()->c.minimap=!c.minimap);toggle("Radar Pokémon",c.pokemonRadar,x,y+82,164,()->c.pokemonRadar=!c.pokemonRadar);}
  else {slide(x,y,"Força glow",c.glowIntensity,0,3,v->c.glowIntensity=v,v->Math.round(v*100)+"%");toggle("Glow animado",c.animatedGlow,x,y+27,164,()->c.animatedGlow=!c.animatedGlow);String[] n={"Unknown","Common","Uncommon","Rare","Ultra Rare","Legendary","Mythical","Ultra Beast","Shiny"};for(int i=0;i<9;i++){int q=i,xx=x+(i%3)*112,yy=y+55+(i/3)*48;toggle("G "+n[i],g(c,q),xx,yy,108,()->sg(c,q,!g(c,q)));toggle("E "+n[i],e(c,q),xx,yy+22,108,()->se(c,q,!e(c,q)));}}
  addDrawableChild(SilverButton.make(Text.literal("Concluir"),b->close()).dimensions(px+12,py+262,336,20).build());}
 private void slide(int x,int y,String n,double a,double lo,double hi,java.util.function.DoubleConsumer s,java.util.function.DoubleFunction<String> f){addDrawableChild(new ConfigSlider(x,y,336,n,a,lo,hi,v->{s.accept(v);mod.config.save();},v->n+": "+f.apply(v)));}
 private void toggle(String n,boolean v,int x,int y,int w,Runnable a){addDrawableChild(SilverButton.make(Text.literal(n+": "+(v?"ON":"OFF")),b->{a.run();mod.config.save();clearAndInit();}).dimensions(x,y,w,20).selected(v).build());}
 private static boolean g(Config c,int i){return switch(i){case 0->c.glowUnknown;case 1->c.glowCommon;case 2->c.glowUncommon;case 3->c.glowRare;case 4->c.glowUltraRare;case 5->c.glowLegendary;case 6->c.glowMythical;case 7->c.glowUltraBeast;default->c.glowShiny;};} private static boolean e(Config c,int i){return switch(i){case 0->c.espUnknown;case 1->c.espCommon;case 2->c.espUncommon;case 3->c.espRare;case 4->c.espUltraRare;case 5->c.espLegendary;case 6->c.espMythical;case 7->c.espUltraBeast;default->c.espShiny;};}
 private static void sg(Config c,int i,boolean v){switch(i){case 0->c.glowUnknown=v;case 1->c.glowCommon=v;case 2->c.glowUncommon=v;case 3->c.glowRare=v;case 4->c.glowUltraRare=v;case 5->c.glowLegendary=v;case 6->c.glowMythical=v;case 7->c.glowUltraBeast=v;default->c.glowShiny=v;}}private static void se(Config c,int i,boolean v){switch(i){case 0->c.espUnknown=v;case 1->c.espCommon=v;case 2->c.espUncommon=v;case 3->c.espRare=v;case 4->c.espUltraRare=v;case 5->c.espLegendary=v;case 6->c.espMythical=v;case 7->c.espUltraBeast=v;default->c.espShiny=v;}}
 @Override public void renderBackground(DrawContext d,int x,int y,float z){}@Override public void render(DrawContext d,int x,int y,float z){d.fill(0,0,width,height,0xbb080b10);StitchTheme.drawBevelPanel(d,px,py,360,292,0xf8121620,StitchTheme.BORDER_OUTER);super.render(d,x,y,z);}@Override public void close(){client.setScreen(parent);}@Override public boolean shouldPause(){return false;}}
